driver=test
interface=ap1
driver_params=test_socket=@RUNDIR@/ap1
ctrl_interface=@RUNDIR@/hostapd-ctrl
ssid=test-6g
hw_mode=a
op_class=131
channel=5
ieee80211ax=1
ieee80211be=1
he_oper_chwidth=0
eht_oper_chwidth=0
wmm_enabled=1
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
sae_password=12345678
sae_pwe=1
ieee80211w=2
logger_stdout=-1
logger_stdout_level=0
