driver=test
interface=ap1
driver_params=test_dir=@RUNDIR@
ctrl_interface=@RUNDIR@/hostapd-ctrl
ssid=test-dir
hw_mode=g
channel=3
ieee80211n=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=12345678
logger_stdout=-1
logger_stdout_level=0
