driver=test
interface=ap1
driver_params=test_socket=@RUNDIR@/ap1
ctrl_interface=@RUNDIR@/hostapd-ctrl
bssid=02:00:00:00:10:02
ssid=test-mld
hw_mode=a
channel=36
ieee80211n=1
ieee80211ac=1
ieee80211ax=1
ieee80211be=1
mld_ap=1
mld_addr=02:00:00:00:10:00
wmm_enabled=1
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
sae_password=12345678
sae_pwe=1
ieee80211w=2
logger_stdout=-1
logger_stdout_level=0
