driver=test
interface=ap1
driver_params=test_socket=@RUNDIR@/ap1
ctrl_interface=@RUNDIR@/hostapd-ctrl
ssid=test-owe
hw_mode=g
channel=1
ieee80211n=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=OWE
rsn_pairwise=CCMP
ieee80211w=2
owe_groups=19 20
logger_stdout=-1
logger_stdout_level=0
