driver=test
interface=ap1
driver_params=test_udp=18701
ctrl_interface=@RUNDIR@/hostapd-ctrl
ssid=test-udp
hw_mode=g
channel=11
ieee80211n=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
sae_password=12345678
ieee80211w=2
logger_stdout=-1
logger_stdout_level=0
