driver=test
interface=ap1
driver_params=test_socket=@RUNDIR@/ap1
ctrl_interface=@RUNDIR@/hostapd-ctrl
ssid=test-eap-radius
hw_mode=g
channel=1
ieee80211n=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee8021x=1
own_ip_addr=127.0.0.1
auth_server_addr=127.0.0.1
auth_server_port=18120
auth_server_shared_secret=radius
acct_server_addr=127.0.0.1
acct_server_port=18130
acct_server_shared_secret=radius
logger_stdout=-1
logger_stdout_level=0
