driver=test
interface=ap1
driver_params=test_socket=@RUNDIR@/ap1
ctrl_interface=@RUNDIR@/hostapd-ctrl
ssid=test-sae
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
sae_password=12345678
sae_pwe=2
ieee80211w=2
beacon_prot=1
logger_stdout=-1
logger_stdout_level=0
