driver=test
interface=ap1
driver_params=test_socket=@RUNDIR@/ap1
ctrl_interface=@RUNDIR@/hostapd-ctrl
ssid=test-suiteb
hw_mode=a
channel=36
ieee80211n=1
ieee80211ac=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-EAP-SUITE-B-192
rsn_pairwise=GCMP-256
group_cipher=GCMP-256
group_mgmt_cipher=BIP-GMAC-256
ieee80211w=2
ieee8021x=1
eap_server=1
eap_user_file=@AUTH_SERV@/eap_user.conf
ca_cert=@AUTH_SERV@/ec2-ca.pem
server_cert=@AUTH_SERV@/ec2-server.pem
private_key=@AUTH_SERV@/ec2-server.key
openssl_ciphers=SUITEB192
logger_stdout=-1
logger_stdout_level=0
