# hostapd acting as a standalone RADIUS/EAP server over loopback UDP
driver=none
interface=as
ctrl_interface=@RUNDIR@/hostapd-ctrl
eap_server=1
eap_user_file=@AUTH_SERV@/eap_user.conf
ca_cert=@AUTH_SERV@/ca.pem
server_cert=@AUTH_SERV@/server.pem
private_key=@AUTH_SERV@/server.key
dh_file=@AUTH_SERV@/dh.conf
radius_server_clients=@AUTH_SERV@/radius_clients.conf
radius_server_auth_port=18120
radius_server_acct_port=18130
eap_server_erp=1
erp_domain=example.com
logger_stdout=-1
logger_stdout_level=0
