ctrl_interface=@RUNDIR@/wpas-ctrl
driver_param=test_socket=@RUNDIR@/no-such-ap scan_time=100 auth_timeout=500 assoc_timeout=500
network={
    ssid="test-open"
    key_mgmt=NONE
    bssid=02:00:00:00:00:99
    scan_freq=2412
}
