ctrl_interface=@RUNDIR@/wpas-ctrl
driver_param=test_socket=@RUNDIR@/ap1
network={
    ssid="test-eap-radius"
    key_mgmt=WPA-EAP
    eap=TTLS
    identity="ttls"
    anonymous_identity="anon"
    password="password"
    ca_cert="@AUTH_SERV@/ca.pem"
    phase2="auth=PAP"
}
