ctrl_interface=@RUNDIR@/wpas-ctrl
driver_param=test_socket=@RUNDIR@/ap1
pmf=2
network={
    ssid="test-suiteb"
    key_mgmt=WPA-EAP-SUITE-B-192
    ieee80211w=2
    eap=TLS
    identity="tls user"
    ca_cert="@AUTH_SERV@/ec2-ca.pem"
    client_cert="@AUTH_SERV@/ec2-user.pem"
    private_key="@AUTH_SERV@/ec2-user.key"
    pairwise=GCMP-256
    group=GCMP-256
    group_mgmt=BIP-GMAC-256
    openssl_ciphers="SUITEB192"
}
