ctrl_interface=@RUNDIR@/wpas-ctrl
driver_param=test_socket=@RUNDIR@/ap1
pmf=2
sae_pwe=1
mld_force_single_link=1
network={
    ssid="test-mld"
    key_mgmt=SAE
    sae_password="12345678"
    ieee80211w=2
}
